### ISSUE TITLE
auto_isolate_from_watchlist throws exception with cbapi version 1.3.6

### ISSUE THREAD

**Issue by askthedragon** [cbcommunity/cbapi-examples#5]
Traceback (most recent call last):
  File "auto_isolate_from_watchlist.py", line 189, in <module>
    validate_watchlist_dict(watchlistsdict)
  File "auto_isolate_from_watchlist.py", line 128, in validate_watchlist_dict
    print "Watchlist: %s, ID: %d" % (key, value)
TypeError: %d format: a number is required, not unicode

**Comment by askthedragon** [comment]
fixed in 207300f
